create evaluation task according to worker num
sql-machine-learning/elasticdl pull request #1783
Opened 2020-02-25 12:05 UTC by QiJune

2020-02-27 09:00 UTC, workingloong commented on elasticdl/python/master/task_dispatcher.py
> -        """
Why do you remove the docstring?

2020-03-06 17:34 UTC, terrytangyuan requested changes

2020-03-06 17:34 UTC, terrytangyuan commented on elasticdl/python/master/task_dispatcher.py
> +                    reader.get_table_size
This is only applicable to readers that has the concept of "table"

2020-03-26 07:16 UTC, chunyang-wen commented on elasticdl/python/data/reader/odps_reader.py
> +        reader = self._get_reader(self._kwargs["table"])
It is better we cache the result and reuse it.

2020-03-26 07:17 UTC, chunyang-wen commented on elasticdl/python/master/task_dispatcher.py
> +        partition = kwargs.get("partition", None) if kwargs else None
`kwargs` is a dict? If so,

```python
partition = kwargs.get("partition", None)
```

2020-06-09 01:08 UTC, closed without merging